export const SignUpStory1 = require('./signup-story1.png')
export const SignUpStory2 = require('./signup-story2.png')
export const SignUpStory3 = require('./signup-story3.png')
export const PlanOverViewBg = require('./plan-cover-bg.png')
export const ProfileImage = require('./profile-img.png')